student_model:
  model_name_or_path: Qwen/Qwen2-0.5B
  flash_attn: fa2
  use_unsloth: false
  output_attentions: true

teacher_model:
  model_name_or_path: Qwen/Qwen2-1.5B
  flash_attn: fa2
  use_unsloth: false
  output_attentions: true

data:
  seed: 42
  text_field: "text"
  train_datasets:
    - path: mlabonne/FineTome-100k
      template: sharegpt
      num_samples: 100
  test_size: 0.2
  streaming: false

tokenizer:
  template: "{% for message in messages %}{% if loop.first and messages[0]['role'] != 'system' %}{{ '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n' }}{% endif %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"

distill:
  type: logits
  max_seq_length: 1024
  sft_config:
    output_dir: './results'
    num_train_epochs: 1
    per_device_train_batch_size: 1
    gradient_accumulation_steps: 1
    eval_strategy: steps
    eval_steps: 100
    save_steps: 2000
    logging_steps: 1
    learning_rate: 2.0e-5
    weight_decay: 0.05
    warmup_ratio: 0.1
    lr_scheduler_type: 'cosine'
    resume_from_checkpoint: null
    fp16: False
    bf16: True
    max_grad_norm: 1.0
    group_by_length: False
  distillation_args:
    temperature: 2.0
    alpha: 0.5
