student_model:
  model_name_or_path: HuggingFaceTB/SmolLM2-135M-Instruct
#  model_name_or_path: Qwen/Qwen2-0.5B
  flash_attn: fa2
  use_unsloth: false
  output_attentions: true
#  enable_liger_kernel: true

teacher_model:
  model_name_or_path: HuggingFaceTB/SmolLM2-360M-Instruct
#  model_name_or_path: Qwen/Qwen2-1.5B
  flash_attn: fa2
  use_unsloth: false
  output_attentions: true
#  enable_liger_kernel: true
#  quantization_bit: 8
#  quantization_method: gptq

data:
  seed: 0
  text_field: "text"
  train_datasets:
    - path: mlabonne/FineTome-100k
      seed: 42
      template: sharegpt
      num_samples: 100
  test_size: 0.2
  streaming: false

distill:
  type: layers
  max_seq_length: 1024
  sft_config:
    output_dir: './results'
    num_train_epochs: 1
    per_device_train_batch_size: 1
    gradient_accumulation_steps: 1
    save_steps: 1000
     # max_steps: 15000, # need to specify with streaming enabled
    logging_steps: 1
    learning_rate: 2.0e-5
    weight_decay: 0.05
    warmup_ratio: 0.1
    lr_scheduler_type: 'cosine'
    resume_from_checkpoint: None  # Set to a path or True to resume from the latest checkpoint
    fp16: False
    bf16: True
    max_grad_norm: 1.0
    group_by_length: False
  distillation_args:
    temperature: 2.0
    alpha: 0.5